### PR TITLE
Feature sql retention

### PR DESCRIPTION
**Pull request by andreabringhurst**
This feature branch makes changes to the retention sql. The goal is to provide the basic data needed to create retention metrics, and to have this sql be consistent with the rest of the sql in utDataStoR.

cohort retention 
- added documentation about the sql
- added term description, season, and year
- added cohort specific information
- removed student identifying information
- added gender description
- changed the way the dates were pulled and extended the years the query ran to allow for retention data over greater amounts of time
- made the sql consistent with other sql in utDataStoR

term-to-term retention
- added documentation about the sql
- added term description, season, and year
- added graduation and completer credentials so the return rate can be calculated
- removed student identifying information
- added degree seeking, student level, student type and full-time part-time indicators which are useful in retention calculations
- added gender description
- created consistency in the cohort_desc naming
- changed the way the dates were pulled
- added where is_enrolled_census
- made the sql consistent with other sql in utDataStoR

### CODE REVIEW

**Review by JoyBaule — APPROVED** [review]
@andreabringhurst I ran each of these queries to test, these are returning the expected results/look great.

**Review by JoyBaule — APPROVED** [review]
I have also reviewed and run this query, it returns expected results.

**Review by cdemkegit — APPROVED** [review]

**Review by mkhassan-isu — APPROVED** [review]

**Review by MattNickodemus — APPROVED** [review]

**Comment by andreabringhurst** [comment]
@cdemkegit @MattNickodemus I am moving this to paused, like I did with issue #7. It is the last of the sql but needs time to be approved. It can be done in the next milestone.

**Comment by andreabringhurst** [comment]
This pull request has been moved to the current milestone. We have reviewed this code in code review.

**Comment by andreabringhurst** [comment]
Approved at code review on 20241121.

**Pull request merged**
